app/src/main/java/com/poupa/vinylmusicplayer/loader/TopAndRecentlyPlayedTracksLoader.java, app/src/main/java/com/poupa/vinylmusicplayer/provider/HistoryStore.java
For the not recently played smart playlist, put the not played (i.e playcount = 0) tracks first.
Currently, those would be put at the end of the list since they are often the newly added ones.
=> Place the not played tracks first in the not recently played list

CHANGELOG.md
I noticed the version numbers increased, but the dates went back in time ;)
=> changelog: fix date typos

app/src/main/res/values-es-rES/strings.xml
Cambio del verbo 'resetear' por una opción válida, como es 'restablecer'.
=> Cambio del verbo 'resetear' por 'restablecer'

app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/PlayingQueueAdapter.java
fixes #211
The snackbar is commented:
> If playing and currently playing song is removed, then added back, then play it at current song progress
This was not true. The app was playing the song at queue index zero, rather than the currently playing song. The queue index values change when a song is removed, so the snackbar needs to know if the song was playing before it was dismissed instead of checking index values after.
=> fix playing wrong song when restoring to play queue

app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java, app/src/main/java/com/poupa/vinylmusicplayer/util/MusicUtil.java, app/src/main/java/com/poupa/vinylmusicplayer/util/PreferenceUtil.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/pref_playlists.xml
This is a new feature.
If enabled (via settings), a new 'Skipped songs' playlist is created and filled with songs that are manually/explicitly skipped during playback.
Can be considered as a reverse concept of "Favorites" songs. In my case, this helps song triage afterwards.
=> Skipped songs

app/src/main/java/com/poupa/vinylmusicplayer/loader/AlbumLoader.java, app/src/main/java/com/poupa/vinylmusicplayer/loader/ArtistLoader.java, app/src/main/java/com/poupa/vinylmusicplayer/loader/SongLoader.java, app/src/main/java/com/poupa/vinylmusicplayer/loader/SortedLongCursor.java, app/src/main/java/com/poupa/vinylmusicplayer/loader/TopAndRecentlyPlayedTracksLoader.java, app/src/main/java/com/poupa/vinylmusicplayer/model/Playlist.java, app/src/main/java/com/poupa/vinylmusicplayer/provider/HistoryStore.java
Originated from https://github.com/AdrienPoupa/VinylMusicPlayer/pull/271.
This PR reduces UI lag due that are related to building the dynamic playlists, at least to make the app more usable in my case.
The change is quite small, if speed is still an issue a more radical approach might be needed later.
--
- Refactoring of 'not recently played' underlying code to speedup a bit;
- Refactoring of history.db cleanup of orphan ID to mass-remove if
possible
=> Reduce UI lag

app/src/main/java/com/poupa/vinylmusicplayer/loader/AlbumLoader.java, app/src/main/java/com/poupa/vinylmusicplayer/loader/ArtistLoader.java
Partial fix for https://github.com/AdrienPoupa/VinylMusicPlayer/issues/67 and for https://github.com/AdrienPoupa/VinylMusicPlayer/issues/232
---
The situation:
1. the app internally doesnt make any difference between 'album artist' and 'artist'.
2. it (incorrectly) assumes that there is only 1 artist per album.
3. when a song is a cooperation has multiple artists, there is no commonly agreed way to specify the list of artist (i.e. "A, B" or "A feat. B" or "A;B & C").
Combination of these 3 issues make the display of artist and the navigation inconsistent.
This PR fixes the 2nd item mentioned above.
=> Fix the artist page display where the artist name is wrong if he/she is involved in multi-artists album

app/src/main/java/com/poupa/vinylmusicplayer/appshortcuts/AppShortcutIconGenerator.java
Icon of appshortcut cannot be the same color than background in dark mode
Before:
After:
=> Appshortcut follow correctly the choosen theme

app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AlbumDetailActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/ArtistDetailActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/GenreDetailActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/PlaylistDetailActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/mainactivity/folders/FoldersFragment.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/mainactivity/library/LibraryFragment.java
Some 3dot menu where not following dark theme
Before:
After:
=> Popup menu for material-cab will follow theme

app/src/main/res/layout/activity_playlist_detail.xml
Correction on the playlist layout (as done per genre layout)
- toolbar no longer put an unwanted shadow
- number of title + time as reappear
Before:
After:
=> Playlist detail view as a layout problem

app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AlbumDetailActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/ArtistDetailActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/GenreDetailActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/PlaylistDetailActivity.java
Some detail view like album can have the title text and the toolbar with different color. This commit fix this strange behaviour.
Before:
After:
=> Detail view text color problem

app/src/main/java/com/poupa/vinylmusicplayer/model/Album.java, app/src/main/java/com/poupa/vinylmusicplayer/provider/Discography.java
@soncaokim asking for your review here since Discog is your baby :)
Basically I am just adding a fallback when there is no title/artist/album.
Let me know if that's OK.
Also, how can we fix it for existing users? ie: how to force the discog cache to clear so they can see the filenames again?
=> #294: restore default filenames when a tag is missing

app/src/main/AndroidManifest.xml, app/src/main/java/com/poupa/vinylmusicplayer/util/MusicUtil.java, app/src/main/java/com/poupa/vinylmusicplayer/util/PlaylistsUtil.java
Workaround the Android 10 behaviour change.
This tackles https://github.com/AdrienPoupa/VinylMusicPlayer/issues/248, as well as the impossibility to add folder to blacklist.
To dos:
=> Playlist bug on Android 10

app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/tageditor/AbsTagEditorActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/util/MusicUtil.java
To reproduce:
- Open album tag editor
- Search for last.fm image
- Save
-> crash with IllegalArgumentException, since ContentResolver.insert expects MIME type = image/*.
=> Fix crash (possible due to Android Q) on album art modification

app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/AlbumSongAdapter.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/DB.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/Discography.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/MemCache.java, app/src/main/java/com/poupa/vinylmusicplayer/model/Song.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/tageditor/AbsTagEditorActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/tageditor/SongTagEditorActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/util/MusicUtil.java, app/src/main/res/layout/activity_song_tag_editor.xml, app/src/main/res/values/strings.xml
Fix for https://github.com/AdrienPoupa/VinylMusicPlayer/issues/251
~~Note that this has Discog DB version 4, i.e. conflicting with the discog-v3 branch.~~
Todo:
=> Multi-disc track sorting

app/src/main/java/com/poupa/vinylmusicplayer/loader/ReplayGainTagExtractor.java
Adds support for ReplayGain tags in MP4 files. Standard tag names are preferred, but the tag names written by iTunes and loudgain are also supported.
=> Support ReplayGain in MP4 files

app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java
Related Android log:
```
Service com.poupa.vinylmusicplayer.service.MusicService has leaked IntentReceiver com.poupa.vinylmusicplayer.service.MusicService$3@4051cc that was originally registered here. Are you missing a call to unregisterReceiver()?
```
=> Attempt to fix a crash after extended sleep

app/src/main/java/com/poupa/vinylmusicplayer/adapter/AlbumCoverPagerAdapter.java
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged!
Expected adapter item count: 2243, found: 2242
Pager id: com.poupa.vinylmusicplayer.ci:id/player_album_cover_viewpager
Pager class: class androidx.viewpager.widget.ViewPager
Problematic adapter: class com.poupa.vinylmusicplayer.adapter.AlbumCoverPagerAdapter
at androidx.viewpager.widget.ViewPager.populate(Unknown Source:569)
at androidx.viewpager.widget.ViewPager.populate(Unknown Source:2)
at androidx.viewpager.widget.ViewPager$3.run(Unknown Source:8)
=> Fix crash when a song is removed from queue

app/src/main/java/com/poupa/vinylmusicplayer/discog/MediaStoreBridge.java, app/src/main/java/com/poupa/vinylmusicplayer/service/MediaStoreObserver.java
I'm experiencing the following crash after removing a bunch of song files from the storage.
MediaStore picks it up and delivers a Observer.onChange notification. My guess is that this notification is delivered while the rescan is still in progress, and more removals are yet to be processed.
Discog picks up the notification and start iterating on the new DB content -> crash:
```
02-14 19:24:56.491 15139 29069 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #53
02-14 19:24:56.491 15139 29069 E AndroidRuntime: Process: com.poupa.vinylmusicplayer.ci, PID: 15139
02-14 19:24:56.491 15139 29069 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-14 19:24:56.491 15139 29069 E AndroidRuntime:        at android.os.AsyncTask$4.done(AsyncTask.java:399) …
```
=> Crash songs removal

app/src/main/java/com/poupa/vinylmusicplayer/auto/AutoMediaIDHelper.java, app/src/main/java/com/poupa/vinylmusicplayer/auto/AutoMusicProvider.java, app/src/main/java/com/poupa/vinylmusicplayer/helper/MusicPlayerRemote.java, app/src/main/java/com/poupa/vinylmusicplayer/service/MediaSessionCallback.java, app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java
```
02-21 13:53:24.677  4645  4645 E AndroidRuntime: FATAL EXCEPTION: main
02-21 13:53:24.677  4645  4645 E AndroidRuntime: Process: com.poupa.vinylmusicplayer.ci, PID: 4645
02-21 13:53:24.677  4645  4645 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
02-21 13:53:24.677  4645  4645 E AndroidRuntime:        at com.poupa.vinylmusicplayer.auto.AutoMusicProvider.getQueue(Unknown Source:18)
02-21 13:53:24.677  4645  4645 E AndroidRuntime:        at com.poupa.vinylmusicplayer.auto.AutoMusicProvider.getChildren(Unknown Source:450)
02-21 13:53:24.677  4645  4645 E AndroidRuntime:        at com.poupa.vinylmusicplayer.service.MusicService.onLoadChildren(Unknown Source:31)
02-21 …
```
=> Fixes for Android Auto

app/src/main/java/com/poupa/vinylmusicplayer/dialogs/AddToPlaylistDialog.java, app/src/main/res/values/strings.xml
As a user, I want to avoid adding things to playlists which are already there. This PR solves that issue by letting the user skip adding tracks that are already in the playlist.
=> Add a confirmation dialog to avoid adding duplicate items to playlists

app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/ReplayGainTagExtractor.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/TagExtractor.java
On my setup, this yields 15-25% performance gain on a full library rescan
=> Optimization: Dont open the audio file again in ReplayGainTagExtractor

app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/TagExtractor.java
Provide support for extracting ID3v1 tags.
One has to force a rescan the library to refresh the information.
Fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/398
=> Id3 v1 compat

app/src/main/java/com/poupa/vinylmusicplayer/dialogs/SongDetailDialog.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/TagExtractor.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/tageditor/AbsTagEditorActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/util/MusicUtil.java
This PR offers a limited work around for https://github.com/AdrienPoupa/VinylMusicPlayer/issues/445, where the MP3 tags cannot be extracted from the file by the jaudiotagger lib. 
Following limitations apply:
- The track metadata relies on the OS MediaStore (with known limits - bad support for accented chars, no multiartist support, etc)
- No tag editor
=> Avoid crash on reading MP3 tags on Nougat

app/src/main/java/com/poupa/vinylmusicplayer/auto/AutoMediaIDHelper.java, app/src/main/java/com/poupa/vinylmusicplayer/helper/MusicPlayerRemote.java, app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java
=> Android 11 media notifications

app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/TagExtractor.java
Should fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/447 as well
To force the release year to be refreshed (re-extracted from the ID3 tags), one needs to trigger "Rescan library" via the app's menu
=> When parsing release year from metadata, only consider the first `yyyy` part

app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java, app/src/main/java/com/poupa/vinylmusicplayer/service/PlaybackHandler.java
With this fix, the media player for the next track is set to null when playing the last track with repeat mode disabled. It was previously initialized with the same track, that's why the track was played again. If repeat mode is enabled, it works the same as before. Also, there's no need to try to pause the player when handling message TRACK_WENT_TO_NEXT because the message is not sent for the last track if repeat mode is disabled.
=> Prevent repeating last track when gapless is enabled (fixes #435)

app/src/main/java/com/poupa/vinylmusicplayer/adapter/PlaylistAdapter.java, app/src/main/java/com/poupa/vinylmusicplayer/helper/menu/MenuHelper.java, app/src/main/java/com/poupa/vinylmusicplayer/helper/menu/SongMenuHelper.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AlbumDetailActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/PlaylistDetailActivity.java, app/src/main/res/menu/menu_item_playlist.xml, app/src/main/res/menu/menu_playlist_detail.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles_parents.xml, app/src/main/res/values/values.xml
All menuItem that delete something are red for better indication:
=> Better menuItem visual queue for delete action

app/src/main/java/com/poupa/vinylmusicplayer/util/PlayingSongDecorationUtil.java
Fixes #189.
Need input on whether this change is ok for the case in which showAlbumCover is true, or if GONE is better suited for that case.
=> Set imageText visibility to INVISIBLE from GONE to allow reordering current song in queue

app/src/main/java/com/poupa/vinylmusicplayer/adapter/PlaylistAdapter.java, app/src/main/java/com/poupa/vinylmusicplayer/helper/menu/MenuHelper.java, app/src/main/java/com/poupa/vinylmusicplayer/helper/menu/SongMenuHelper.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AlbumDetailActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/ArtistDetailActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/GenreDetailActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/PlaylistDetailActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/mainactivity/folders/FoldersFragment.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/mainactivity/library/LibraryFragment.java, app/src/main/res/menu/menu_cannot_delete_single_songs_playlist_songs_selection.xml, app/src/main/res/menu/menu_media_selection.xml, app/src/main/res/menu/menu_playlists_selection.xml, app/src/main/res/menu/menu_playlists_songs_selection.xml
As @soncaokim pointed out in https://github.com/AdrienPoupa/VinylMusicPlayer/pull/520 for the multiselection menu (like playlist folder or main activity cab menu) I have forgotten to add the new red accent color, this is now corrected:
=> Adding missing red menu item delete in all multiselecion menu

app/src/main/java/com/poupa/vinylmusicplayer/appwidgets/base/BaseAppWidget.java
This adds a darkmode for the widget, that follows the apps settings.
I also suggest to add a bigger corner-radius, to make the widget look more consistent with current android-versions. 
I already implemented those corners, just tell me if i should include them here or in a new pr or not!
=> add darkmode to BaseAppWidget

app/src/main/java/com/poupa/vinylmusicplayer/discog/Discography.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/MemCache.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/SyncWithMediaStoreAsyncTask.java, app/src/main/java/com/poupa/vinylmusicplayer/loader/TopAndRecentlyPlayedTracksLoader.java, app/src/main/java/com/poupa/vinylmusicplayer/misc/queue/StaticPlayingQueue.java, app/src/main/java/com/poupa/vinylmusicplayer/provider/MusicPlaybackQueueStore.java, app/src/main/java/com/poupa/vinylmusicplayer/provider/StoreLoader.java, app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/card/CardPlayerFragment.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/flat/FlatPlayerFragment.java
To reproduce:
- Start a playing queue with all songs
- Stop the app
- Remove some songs from the device
- Restart the app
=> Fix crash on restoring queue after song removal

app/src/main/java/com/poupa/vinylmusicplayer/util/PackageValidator.kt, app/src/main/res/xml/allowed_media_browser_callers.xml
To reproduce:
- search for "driving mode" in Google Assistant
- open media playing widget that corresponds to Vinyl
- tap on "browse vinyl"
- tap on "open vinyl"
- crash with the folloing stack trace
```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
at com.poupa.vinylmusicplayer.util.PackageValidator.isKnownCaller(Unknown Source:196)
at com.poupa.vinylmusicplayer.service.MusicService.onGetRoot(Unknown Source:2)
at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21.onGetRoot(Unknown Source:107)
at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$MediaBrowserServiceApi21.onGetRoot(Unknown Source:15)
at android.service.media.MediaBrowserService$ServiceBinder$1.run(MediaBrowserService.java:229)
at …
```
=> Fix crash launching from Google Assistant

app/build.gradle
In the long run, this is not a desirable fix.
However it helps avoiding the regression with API 31.
=> Stick to API 29, avoid regression in song deletion

app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java
This is an attempt to fix the following crash.
The approach chosen is to ignore the saved queue - i.e. degraded service.
```
java.lang.ArrayIndexOutOfBoundsException: length=1620; index=-1
at java.util.ArrayList.get(ArrayList.java:439)
at com.poupa.vinylmusicplayer.misc.queue.StaticPlayingQueue.restoreUniqueId(Unknown Source:40)
at com.poupa.vinylmusicplayer.misc.queue.StaticPlayingQueue.<init>(Unknown Source:63)
at com.poupa.vinylmusicplayer.service.MusicService.restoreQueuesAndPositionIfNecessary(Unknown Source:99)
at com.poupa.vinylmusicplayer.service.PlaybackHandler.handleMessage(Unknown Source:28)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:250)
at android.os.HandlerThrbead.run(HandlerThread.java:67)
```
Not reproducible, probably …
=> Queue restore crash

.circleci/config.yml
Fixes the deprecation warning
> You’re using a [deprecated Docker convenience image.](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) Upgrade to a next-gen Docker convenience image.
=> Upgrade to new CircleCI image

app/src/main/java/com/poupa/vinylmusicplayer/sort/SongSortOrder.java
This should fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/582
=> Use song title to stabilize the sorting if disc+track are equals or missing

app/src/main/res/values/styles_parents.xml
The current Black theme's Now Playing view is grey and this has always been the case since time immemorial.
This offers a tried and tested fix I have been using in my own private Phonograph builds for years now, so it would be great to see this finally implemented for more people to enjoy.
Signed-off-by: Sai <saiprasanna@me.com>
=> Fix Black (OLED) theme to actually be black.

app/src/main/java/com/poupa/vinylmusicplayer/helper/SearchQueryHelper.java, app/src/main/java/com/poupa/vinylmusicplayer/loader/GenreLoader.java, app/src/main/java/com/poupa/vinylmusicplayer/loader/PlaylistLoader.java, app/src/main/java/com/poupa/vinylmusicplayer/loader/PlaylistSongLoader.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/MainActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/util/StringUtil.java
This allows AIs to open playlist by name.
- https://developer.android.com/guide/components/intents-common#PlaySearch
I've been testing using the intents from https://github.com/hobbycommandline/Hobby-Voice-Command-Line but I've been consulting the official google docs and the code I wrote complies with google's standards.
=> Add playlist/genre to the search by query intent. Fix a crash on failed search; interpret empty query search as play all songs

app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/card/CardPlayerFragment.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/flat/FlatPlayerFragment.java
fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/620
rationale: https://stackoverflow.com/questions/45419378/disabling-animations-on-a-device-crashes-the-app
I tested manually, and it stopped the crashes I was experiencing
=> Fix a crash due to #620

app/src/main/java/com/poupa/vinylmusicplayer/sort/ArtistSortOrder.java
Addresses #581 
First of all, thanks to the maintainers of this project ! I have been using Vinyl for the past couple of years or so, and its overall quality helped me change the way I listen to music.
I would like to contribute back to this project which brings me so much.
As described in the open issue, this behavior is quite common in music apps (ex: Sonos, Spotify) and certainly helps listeners of english-named artists to unclutter their "T" letter.
=> Feat: Ignore "the" and "a" prefixes when sorting artists

.github/workflows/ci.yml, README.md
- Promote the last build APK from master to a public accessible download link in README.md
Behind the scenes, this relies on a moving `pre-release` tag, updated each time there is a sucessful build; and on the Github's release facility.
- Replace "Get it on ..." image links by dynamic badges showing the available version on the respective distribution channel.
See demo: https://github.com/VinylMusicPlayer/VinylMusicPlayer/tree/upstream-contrib/ci-show-last-build-arrifact
=> upstream-contrib: Show last CI build artifact 

app/src/main/assets/LICENSES.md, app/src/main/java/com/poupa/vinylmusicplayer/dialogs/MarkdownViewDialog.java, app/src/main/res/layout/dialog_markdown_view.xml, script/build-licenses-page
I am a fan of the scripted .md file but the user experiences is a little bit glaring in my opinion.
I this PR I am adding inertial scrolling, removing all the header line but keeping some for licenses:
=> Cleaner markdown visualisation

app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/PlayingQueueAdapter.java, app/src/main/java/com/poupa/vinylmusicplayer/dialogs/DeleteSongsDialog.java, app/src/main/java/com/poupa/vinylmusicplayer/helper/MusicPlayerRemote.java, app/src/main/java/com/poupa/vinylmusicplayer/helper/PrevNextButtonOnTouchListener.java, app/src/main/java/com/poupa/vinylmusicplayer/misc/queue/StaticPlayingQueue.java, app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/AbsPlayerFragment.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/MiniPlayerFragment.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/PlayerAlbumCoverFragment.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/card/CardPlayerFragment.java, app/src/main/java/com/poupa/vinylmusicplayer/util/MusicUtil.java, app/src/main/java/com/poupa/vinylmusicplayer/util/PlaylistsUtil.java
The "Skipped songs" was updated only if one presses on the Next button.
Now it detects Previous button, UI swipe/fling gestures as well.
Todo
=> Refactor Skipped songs implementation

app/src/main/java/com/poupa/vinylmusicplayer/dialogs/BottomSheetDialog/BottomSheetDialogWithButtons.java, app/src/main/java/com/poupa/vinylmusicplayer/helper/MusicPlayerRemote.java, app/src/main/java/com/poupa/vinylmusicplayer/preferences/SongConfirmationPreference.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/SettingsActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/util/PreferenceUtil.java, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/pref_now_playing_screen.xml
To resolve user feedback in: https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/658  
And new request https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/708  
This add a preference to choose between confirmation dialog or some default action:
By default it is set to replace queue like in 1.4
=> Enqueue song action can now be choosen in preference

app/src/main/java/com/poupa/vinylmusicplayer/dialogs/BottomSheetDialog/BottomSheetDialog.java, app/src/main/java/com/poupa/vinylmusicplayer/dialogs/BottomSheetDialog/BottomSheetDialogWithButtons.java
Circumvent the CAB/Toolbar bad icon color - the curved arrow in the screenshot below
Related references:
- https://stackoverflow.com/questions/28219178/toolbar-icon-tinting-on-android
- https://stackoverflow.com/questions/26780046/menuitem-tinting-on-appcompat-toolbar
- https://issuetracker.google.com/issues/37127128
=> Cab icon tint

app/src/main/java/com/poupa/vinylmusicplayer/adapter/PlaylistAdapter.java, app/src/main/java/com/poupa/vinylmusicplayer/dialogs/helper/DeleteSongsDialogAndroidR.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/TagExtractor.java, app/src/main/java/com/poupa/vinylmusicplayer/helper/menu/PlaylistMenuHelper.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/tageditor/AbsTagEditorActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/tageditor/AlbumTagEditorActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/tageditor/SongTagEditorActivity.java, app/src/main/java/com/poupa/vinylmusicplayer/util/MusicUtil.java, app/src/main/java/com/poupa/vinylmusicplayer/util/OopsHandler.java, app/src/main/java/com/poupa/vinylmusicplayer/util/SAFUtil.java
Fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/802
Note that this fixes the app crash, not the cause of the (diverse) exception that trigger the copy of exception to the clipboard
=> Dont crash if OopsHandler is called from a background (non-UI) thread

app/src/main/java/com/poupa/vinylmusicplayer/misc/queue/StaticPlayingQueue.java, app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java, app/src/test/java/com/poupa/vinylmusicplayer/StaticPlayingQueueTest.java
When restoring the playing queue, make sure to include the repeat setting, otherwise it will default back to none.
Fixes #663.
=> Fix repeat setting not being restored

.github/workflows/ci.yml, script/prepare-new-release
i.e. leave the tagging as a manual step, post-merge
=> Refrain from rushing out a new release on every new tag

app/src/main/AndroidManifest.xml
Item was showing "No equalizer found."
Tomcat was showing e.g.:
```
AppsFilter system_server I interaction: PackageSetting{2ed00e2 com.poupa.vinylmusicplayer.ci.debug/10125} -> PackageSetting{2d494d8 com.android.musicfx/10062} BLOCKED
```
=> Fix equalizer settings being marked unavailable in the settings

app/src/main/java/com/poupa/vinylmusicplayer/App.java, app/src/main/java/com/poupa/vinylmusicplayer/dialogs/SongDetailDialog.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/DB.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/Discography.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/MemCache.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/ReplayGainTagExtractor.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/TagExtractor.java, app/src/main/java/com/poupa/vinylmusicplayer/model/Song.java, app/src/main/java/com/poupa/vinylmusicplayer/service/MultiPlayer.java, app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java, app/src/main/java/com/poupa/vinylmusicplayer/util/PreferenceUtil.java, app/src/main/java/com/poupa/vinylmusicplayer/util/SAFUtil.java, app/src/main/res/values-fr/strings.xml, app/src/main/res/values/strings.xml
As mentioned in #785, positive replay gains were not applied reliably, because MediaPlay.setVolume only accepts values between 0.0 and 1.0.
This PR introduces DynamicsProcessing in the MultiPlayer: it allows both positive and negative gains on its input gain stage, so there is no need to reduce the replay gain preamp value in the settings any more to benefit from positive replay gains.
DynamicsProcessing is only available from Android P, so the volume-based method is still used for older phones. In this case, the conversion from dB to linear gain has been moved from the MusicService into the MultiPlayer, since DynamicsProcessing input gain takes values in dB.
Also, as per the [ReplayGain spec](https://wiki.hydrogenaud.io/index.php?title=ReplayGain_1.0_specification#Reduced_gain), the …
=> Use DynamicsProcessing to apply positive replay gains in a robust way

app/src/main/java/com/poupa/vinylmusicplayer/service/MediaStoreObserver.java, app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java, app/src/main/java/com/poupa/vinylmusicplayer/service/ThrottledSeekHandler.java
Refactor the MusicService class, introduce `synchronized` blocks to protect data fields from competing access from multiple threads.
Fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/851
=> Fix race cond - 2

app/src/main/res/values-de/strings.xml
I added the new strings, especially for reporting crashes / bugs.
I also reordered the strings to be in sync with the main values.xml
There is one thing with the very last string in the main values.xml, which looks a bit incomplete:
```
<string name="saf_guide_slide_description_android13">This will allow the app to modify or delete song when you ask for it\nGive the access right to the most important music folder\nAny file outside of it can be modify but android will ask for a temporary permission each time\n\nYou can also instead configure the app to always asked for permission before any right action\nWith a changeable settings</string>
```
There are two issues with this string. First, there are two little typos ("can be modify" -> "can be modified", "asked" -> "ask") and the last …
=> Updated German translations

app/src/main/java/com/poupa/vinylmusicplayer/service/notification/PlayingNotificationImplApi24.java
@soncaokim It turned out the problem was with the fancy notification grabbing the mediaSession before a metadata had been set.  My change does the simplest thing I could think of to prevent this.  It just checks to make sure the metadata isn't null when building the notification.
I tested this on my phone and it prevents the crash.  The only downside seems to be that the notification control thing isn't fancy, until you hit play, at which point it restyles itself.
The precise steps to reproduce look like this:
1. uninstall app
2. install app
3. let it build library enough to find a song
4. play a few seconds of the song
5. pause the song
6. close the app
7. reopen the app
This always crashed the system UI before, and with this patch, it no longer crashes.
FWIW, the reason your changes to …
=> fixes #853, the system UI notification crash

app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/GenreDetailActivity.java, app/src/main/res/menu/menu_genre_detail.xml
Add context menu to genre activity
- Play Next
- Add to playing queue
- Add to playlist...
This adds identical functionality for genres to these 3 features found in artist play activity.
This is related to #906 and implements my desired functionality.
=> Add context menu to genre activity

app/src/main/java/com/poupa/vinylmusicplayer/discog/MemCache.java
re: #773 
edit 2:
I have verified this change is compliant with all existing genre uses in the app, and should not cause issues.
edit:
from linux if you want to set multiple genres for a song you can do
```bash
eyeD3 YOUR_SONG --genre="Alternative;Indie"
```
=> allow genre splitting based on typical split characters

app/src/main/res/layout/activity_album_tag_editor.xml, app/src/main/res/layout/activity_song_tag_editor.xml, app/src/main/res/values/strings.xml
Adds new string and updates album and song tag editors to allow the one-per-line style input. Genre parsing already handles this, so this was only a UI change
=> add multi-line genre editing

app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/tageditor/AbsTagEditorActivity.java
Re: #863
In all technicality, this check does nothing and has no side effects. We don't gate solely on SD card access for other API versions, and the checking state to request any necessary permissions for the code occurs elsewhere. So we should not do this check here.
=> Allow tag editor to function on API 30+

app/build.gradle
This fork supports reading metadata from Opus files
Opus support backported from https://github.com/Kaned1as/jaudiotagger
Fixes: #780, #781
=> Use an updated fork with Opus support

app/src/main/java/com/poupa/vinylmusicplayer/dialogs/SongDetailDialog.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/DB.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/Discography.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/MemCache.java, app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/TagExtractor.java, app/src/main/java/com/poupa/vinylmusicplayer/model/Song.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/tageditor/AbsTagEditorActivity.java
Add missing implementation to support multi-genre (loading and saving)
=> Fix multi genres

app/src/main/java/com/poupa/vinylmusicplayer/discog/MemCache.java
If a Song's `artists` field is empty, but `album artists` field is not (hence the song is attached to an artist via the latter field), then a dangling "Unknown Artist" item is shown in the artist browser with no attached album.
This fixes this annoyance.
=> Dangling unknown artist

CHANGELOG.md, app/build.gradle, app/src/main/assets/contributors.csv
* Fix save playlist android9 by @soncaokim in https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/944
* Fix dangling unknown artist by @soncaokim in https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/956
* Fix crash on select dupe song in playlist by @soncaokim in https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/950
* Fix stale notification by @soncaokim in https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/961
* Silence logcat warning about deprecated use of stream type by @soncaokim in https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/963
**Full Changelog**: https://github.com/VinylMusicPlayer/VinylMusicPlayer/compare/1.8.0...1.8.1
=> Next release 1.8.1

app/src/main/java/com/poupa/vinylmusicplayer/service/notification/IdleNotification.java
Closes #952
I chose this approach because it does not clutter `MusicService.java`, however the right approach probably would be to annotate `IdleNotification` with `@RequiresApi(Build.VERSION_CODES.TIRAMISU)` and add the necessary ifs in `MusicService.java`. I can do that too if desired.
=> Resolve "Android 8: Unnecessary "Vinyl is running" notification #952"

app/src/main/java/com/poupa/vinylmusicplayer/adapter/PlaylistAdapter.java, app/src/main/java/com/poupa/vinylmusicplayer/adapter/SongFileAdapter.java, app/src/main/java/com/poupa/vinylmusicplayer/adapter/album/AlbumAdapter.java, app/src/main/java/com/poupa/vinylmusicplayer/adapter/artist/ArtistAdapter.java, app/src/main/java/com/poupa/vinylmusicplayer/adapter/base/AbsMultiSelectAdapter.java, app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/AbsOffsetSongAdapter.java, app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/OrderablePlaylistSongAdapter.java, app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/SongAdapter.java, app/src/main/java/com/poupa/vinylmusicplayer/dialogs/AddToPlaylistDialog.java, app/src/main/java/com/poupa/vinylmusicplayer/dialogs/RemoveFromPlaylistDialog.java, app/src/main/java/com/poupa/vinylmusicplayer/dialogs/helper/DeleteSongsDialogApi19.java, app/src/main/java/com/poupa/vinylmusicplayer/dialogs/helper/DeleteSongsDialogApi30.java, app/src/main/java/com/poupa/vinylmusicplayer/dialogs/helper/DeleteSongsHelper.java, app/src/main/java/com/poupa/vinylmusicplayer/helper/MusicPlayerRemote.java, app/src/main/java/com/poupa/vinylmusicplayer/helper/menu/SongsMenuHelper.java, app/src/main/java/com/poupa/vinylmusicplayer/misc/queue/StaticPlayingQueue.java, app/src/main/java/com/poupa/vinylmusicplayer/provider/SongList.java, app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/mainactivity/folders/FoldersFragment.java, app/src/main/java/com/poupa/vinylmusicplayer/util/PlaylistsUtil.java
=> Refactor multi select

app/src/main/java/com/poupa/vinylmusicplayer/helper/MusicPlayerRemote.java, app/src/main/java/com/poupa/vinylmusicplayer/misc/queue/StaticPlayingQueue.java, app/src/main/java/com/poupa/vinylmusicplayer/model/smartplaylist/AbsSmartPlaylist.java, app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java, app/src/main/java/com/poupa/vinylmusicplayer/service/PlaybackHandler.java, app/src/main/java/com/poupa/vinylmusicplayer/service/QueueSaveHandler.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/card/CardPlayerFragment.java, app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/flat/FlatPlayerFragment.java, app/src/main/java/com/poupa/vinylmusicplayer/util/PreferenceUtil.java, app/src/main/java/com/poupa/vinylmusicplayer/util/SafeToast.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/pref_development.xml
This new feature for now is controlled by an opt-in flag in Settings.
I'll enable by default/remove the flag in the future if no negative user feedback.
To dos:
=> Keep the queue in sync with changes from MediaStore (removal, update)

app/src/main/java/com/poupa/vinylmusicplayer/service/notification/AbsNotification.java, app/src/main/java/com/poupa/vinylmusicplayer/service/notification/IdleNotification.java
The foreground service requires a notification to be posted asap
Related to #952 (the original bug report), #978 (the attempted fix) and https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/816#issuecomment-2049757579 (the regression report)
=> Fix ANR on app startup if the queue is empty

app/src/main/java/com/poupa/vinylmusicplayer/glide/audiocover/AbsCoverFetcher.java, app/src/main/java/com/poupa/vinylmusicplayer/glide/audiocover/FileCoverFetcher.java, app/src/main/java/com/poupa/vinylmusicplayer/glide/audiocover/SongCoverFetcher.java
Possibly fixes #816 on Android 13+, by relying on MediaStore to detect and scan the external folder image
Note that this is only a workaround, with limitations:
=> Fallback to cover image scanned and stored in MediaStore

app/src/main/java/com/poupa/vinylmusicplayer/discog/SyncWithMediaStoreAsyncTask.java
Fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/1043, https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/1042, https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/1024, https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/988
=> Fix NPE (the result object can indeed be null)

.github/workflows/ci.yml, script/build-release
Two changes:
- Upgrade GH Actions plugin to comply with Node.js 16 deprecation
- Dont blindly overwrite the signing config if the app is built via GH Actions. Do this only if the signing config is effectively specified
=> CI updates

app/src/main/res/layout/activity_artist_detail.xml
Old Android doesnt support the vector drawable in XML
See https://developer.android.com/studio/write/vector-asset-studio
=> Fix crash on Android 19 with go to artist

app/src/main/java/com/poupa/vinylmusicplayer/provider/PreferencesBackedSongList.java
Heeeey, how is it going?
I thought it would be a good idea to move 'Favorites' playlist on top of the 'Static playlists'. Now it lost somewhere in the middle and sometimes it is hard to find. 
Long story short:
Surely it's just an example of code, you know better how to implement this. In case you find it interesting. 
Thank you and keep up the good job!
=> Always keep 'Favorites' playlist on top
