app/src/main/java/com/poupa/vinylmusicplayer/provider/HistoryStore.java

This is related to https://github.com/AdrienPoupa/VinylMusicPlayer/pull/123#issuecomment-475132128
Thanks

forgot reversing the selection condition

---

.gitignore
app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/PlayingQueueAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/dialogs/DeleteSongsDialog.java

Handle mutiple cases: remove from queue via song menu, remove from queue via swipe, delete song from storage.

Continue playing on song removal

---

.circleci/config.yml
app/src/main/java/com/poupa/vinylmusicplayer/loader/SongLoader.java

This is the fix for https://github.com/AdrienPoupa/VinylMusicPlayer/issues/140, based off the version 0.21.0.
I ll check with the changes of 0.21.1

Crash on fresh start

---

app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java
app/src/main/java/com/poupa/vinylmusicplayer/service/notification/PlayingNotificationImpl.java
app/src/main/java/com/poupa/vinylmusicplayer/service/notification/PlayingNotificationImpl24.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/base/AbsMusicServiceActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/util/MusicUtil.java
app/src/main/res/layout/notification.xml
app/src/main/res/layout/notification_big.xml

Address #151 
I'm personally unsure whether to keep the button in the small notification, it may make things a little cramped.

Add favorite button to notifications

---

app/src/main/java/com/poupa/vinylmusicplayer/helper/MusicPlayerRemote.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/AbsPlayerFragment.java
app/src/main/java/com/poupa/vinylmusicplayer/util/MusicUtil.java

Add current play queue position and length alongside playtime remaining

Add play queue progress to up next

---

app/src/main/AndroidManifest.xml
app/src/main/res/drawable/splash.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

Fix white flash on startup by adding a startup screen
Screenshot:

Add startup splash screen - fix white flash

---

app/src/main/java/com/poupa/vinylmusicplayer/deezer/Data.kt
app/src/main/java/com/poupa/vinylmusicplayer/deezer/DeezerApiService.kt
app/src/main/java/com/poupa/vinylmusicplayer/deezer/DeezerResponse.kt
app/src/main/java/com/poupa/vinylmusicplayer/glide/artistimage/ArtistImageFetcher.java
app/src/main/java/com/poupa/vinylmusicplayer/glide/artistimage/ArtistImageLoader.java

Use deezer for fetching artist images

---

app/build.gradle
build.gradle

Going to eventually remove the legacy AndroidX packages / migrate to Material packages properly.

Update Kotlin, organize dependencies

---

app/src/main/java/com/poupa/vinylmusicplayer/glide/artistimage/ArtistImageFetcher.java

This should fixes the https://github.com/AdrienPoupa/VinylMusicPlayer/issues/166

Fix crash artist image fetcher

---

app/src/main/res/values-de/strings.xml

Added some missing strings to German translation

updated German translation

---

app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/card/CardPlayerFragment.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/flat/FlatPlayerFragment.java
app/src/main/java/com/poupa/vinylmusicplayer/util/PlayingSongDecorationUtil.java
app/src/main/java/com/poupa/vinylmusicplayer/util/PreferenceUtil.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_now_playing_screen.xml

This PR replaces the playing song indicator icon (currently a broadcasting loud speaker) by a rotating vinyl disc.

Animated playing indicator icon

---

app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/tageditor/AlbumTagEditorActivity.java
app/src/main/res/layout/activity_album_tag_editor.xml

 fix album tag editor deleting 'artist' tag if 'album artist' is empty

---

app/src/main/java/com/poupa/vinylmusicplayer/glide/artistimage/ArtistImageFetcher.java

this is a proposal to avoid pulling deezer's place holder image in artist view.
the detection code is somewhat fragile, any idea to improve is welcomed.

Skip deezer empty image

---

app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/mainactivity/folders/FoldersFragment.java

On my phone, nothing happens if I scan the entire music folder, but scanning the directory for an artist works.
`ListPathsAsyncTask` keeps a weak reference to its callback. When scanning a large folder, the callback gets garbage collected before the task can finish. When scanning a small folder, the task is able to finish and call its callback before the callback is garbage collected.
I have changed the reference to the callback to a strong reference. The task now checks whether the context (instead of the callback) is still in memory to determine whether to continue processing.

Fix scanning large folders

---

app/build.gradle

Fixing todo, catching up https://github.com/AdrienPoupa/VinylMusicPlayer/pull/247

Dependencies version bump

---

app/build.gradle

Revert "Merge pull request #262 from soncaokim/dependencies-version-bump"

---

app/src/main/java/com/poupa/vinylmusicplayer/views/AutoTruncateTextView.java

This fixes the https://github.com/AdrienPoupa/VinylMusicPlayer/issues/169.
@theduffmaster Can you please have a look as well?

Fix the ellipsize bug

---

app/src/main/res/layout-land/fragment_card_player.xml
app/src/main/res/layout/bug_report_card_device_info.xml
app/src/main/res/layout/bug_report_card_report.xml
app/src/main/res/layout/card_about_app.xml
app/src/main/res/layout/card_author.xml
app/src/main/res/layout/card_special_thanks.xml
app/src/main/res/layout/card_support_development.xml
app/src/main/res/layout/fragment_card_player.xml
app/src/main/res/layout/item_grid_card_horizontal.xml

Fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/266

Themes fix

---

app/src/main/java/com/poupa/vinylmusicplayer/adapter/AlbumCoverPagerAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/util/PlayingSongDecorationUtil.java
app/src/main/java/com/poupa/vinylmusicplayer/util/PreferenceUtil.java
app/src/main/java/com/poupa/vinylmusicplayer/util/ViewUtil.java

This should fix https://github.com/AdrienPoupa/VinylMusicPlayer/issues/235

Fallback album image fix

---

app/src/main/res/values-fr/strings.xml

Small correction on the french trad seen after using the app

Small french correction after more usage

---

app/src/main/java/com/poupa/vinylmusicplayer/adapter/PlaylistAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/adapter/album/AlbumAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/adapter/artist/ArtistAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/adapter/base/AbsMultiSelectAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/AbsOffsetSongAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/ArtistSongAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AlbumDetailActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/ArtistDetailActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/GenreDetailActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/PlaylistDetailActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/base/AbsThemeActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/mainactivity/folders/FoldersFragment.java

For a more material design aspect (will also work in multi-select mode)
Result:

Status bar color == toolbar color

---

app/build.gradle

Note that this somehow affects the apk name of other build flavors as well, see https://app.circleci.com/pipelines/github/soncaokim/VinylMusicPlayer/345/workflows/2c4b2b85-9e75-4c15-961c-c1e2cd7a6d4c/jobs/353/artifacts 
If this is an issue, please tell me.

Change APK name, mainly to help debugging/comparing during development

---

app/src/main/java/com/poupa/vinylmusicplayer/util/MusicUtil.java
app/src/main/java/com/poupa/vinylmusicplayer/util/PreferenceUtil.java
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_now_playing_screen.xml

I know you rejected the idea before but as i really like this feature here is a second try with an setting that can enable it (disable by default)
link to original MR: https://github.com/AdrienPoupa/VinylMusicPlayer/pull/286

Track number v2

---

app/src/main/res/values/ic_launcher_background.xml

Resolve issue https://github.com/AdrienPoupa/VinylMusicPlayer/issues/304

Remove white line around app icon (lot of pixelation)

---

app/src/main/java/com/poupa/vinylmusicplayer/appwidgets/base/BaseAppWidget.java

Resolve issue https://github.com/AdrienPoupa/VinylMusicPlayer/issues/296

Big widget get white control button to be seen on more album art

---

app/src/main/java/com/poupa/vinylmusicplayer/discog/DB.java

Attempt to fix https://github.com/AdrienPoupa/VinylMusicPlayer/issues/325

Thread-safe DB operation

---

app/src/main/java/com/poupa/vinylmusicplayer/adapter/album/AlbumAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/SongAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/discog/MemCache.java
app/src/main/java/com/poupa/vinylmusicplayer/helper/SortOrder.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/AlbumLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/SongLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/mainactivity/library/LibraryFragment.java

Fix regression described via https://github.com/AdrienPoupa/VinylMusicPlayer/issues/341 via https://github.com/AdrienPoupa/VinylMusicPlayer/pull/344/commits/2b4089aa76fa3827bb3f0a35d1830007a97b341e

Fix sort order

---

app/src/main/java/com/poupa/vinylmusicplayer/discog/Discography.java
app/src/main/java/com/poupa/vinylmusicplayer/helper/WeakMethodReference.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AlbumDetailActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/ArtistDetailActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/GenreDetailActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/MainActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/PlaylistDetailActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/base/AbsSlidingMusicPanelActivity.java

Remove songs from detail activities after they are deleted

---

app/src/main/java/com/poupa/vinylmusicplayer/discog/Discography.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/MainActivity.java

Misc changes cherry-picked from abandoned attempt to fix zombies tracks (https://github.com/AdrienPoupa/VinylMusicPlayer/pull/358)

Misc change

---

app/src/main/java/com/poupa/vinylmusicplayer/App.java
app/src/main/java/com/poupa/vinylmusicplayer/discog/Discography.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/AlbumLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/ArtistLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/GenreLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/PlaylistSongLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/SongLoader.java

(consequence: inconsistent cache, increase load time, etc)

Fix bug where Discog can be instantiated multiple times

---

app/src/main/java/com/poupa/vinylmusicplayer/discog/MemCache.java

This is most likely to happen to albums with Unicode characters in name

Fix regression: Albums with same name/same artist may be split by MediaStore -> merge them back

---

app/src/main/java/com/poupa/vinylmusicplayer/discog/MemCache.java

Oops, I've missed this during the regression tests

Fix: Feature artist page shows full albums, not just the slice he is part of

---

app/src/main/java/com/poupa/vinylmusicplayer/auto/AutoMusicProvider.java
app/src/main/java/com/poupa/vinylmusicplayer/helper/MusicPlayerRemote.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MediaSessionCallback.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java

While processing the play requests (ie for Auto), dont use the services provided by MusicPlayerRemote proxy to access MusicService.
This proxy does not handling the latter's init/lifecycle, hence may nullify any attempt to use the latter.
This PR probably fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/237

Auto queue stuck

---

app/src/main/java/com/poupa/vinylmusicplayer/service/MultiPlayer.java

As a user, I want my music to continue playing even if there's an error trying to play a track. This PR addresses that by skipping to the next track if possible when the current track has an error.

Skip to the next track when the currently playing one has an error

---

app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java

Fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/407

Fix RG not applied if gapless is enabled 

---

app/src/main/java/com/poupa/vinylmusicplayer/service/MultiPlayer.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java
app/src/main/java/com/poupa/vinylmusicplayer/service/ThrottledSeekHandler.java

Should fix https://github.com/AdrienPoupa/VinylMusicPlayer/issues/221 and https://github.com/AdrienPoupa/VinylMusicPlayer/issues/410

Notification progress slider

---

app/src/main/java/com/poupa/vinylmusicplayer/adapter/PlaylistAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/provider/SongPlayCountStore.java

Async load playlist info string

Speedup on init

---

app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/PlayingQueueAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/dialogs/AddToPlaylistDialog.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java

Minor changes - see the commits

Minor queue mgmt changes

---

.circleci/merge-feature-branches
.circleci/sync-tracking-branches

Merge the special cont-integ branch to master, to avoid divergence. 
No impact on the build nor on the code unless a build is triggered from this branch.

Cont integ

---

app/src/main/java/com/poupa/vinylmusicplayer/helper/MusicPlayerRemote.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/ArtistDetailActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/util/MusicUtil.java

- Crash on using LastFM data usage on unknown artist
- Crash deleting a bunch of songs while playing
```
05-18 22:59:46.077 21693 21693 E AndroidRuntime: FATAL EXCEPTION: main
05-18 22:59:46.077 21693 21693 E AndroidRuntime: Process: com.poupa.vinylmusicplayer.ci, PID: 21693
05-18 22:59:46.077 21693 21693 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.poupa.vinylmusicplayer.queuechanged flg=0x10 } in com.poupa.vinylmusicplayer.ui.activities.base.AbsMusicServiceActivity$MusicStateReceiver@b5d343b
05-18 22:59:46.077 21693 21693 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1575)
05-18 22:59:46.077 21693 21693 E AndroidRuntime:        at …
```

Fix crashes

---

app/src/main/java/com/poupa/vinylmusicplayer/dialogs/SongDetailDialog.java

This fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/457

Try to contain impact of exception thrown by AudioFileIO.read

---

app/src/main/java/com/poupa/vinylmusicplayer/helper/PrevNextButtonOnTouchListener.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/card/CardPlayerPlaybackControlsFragment.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/flat/FlatPlayerPlaybackControlsFragment.java

Thus, I have just taken the code from the other fragment and past it
See issue84 and https://github.com/AdrienPoupa/VinylMusicPlayer/pull/404

Fast forwad was not put on flat palyer

---

app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/MultiValuesTagUtil.java

no guarantee that the underlying Cursor implementation doesnt return null.
Fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/472

Fix NPE on artist name splitting

---

app/src/main/java/com/poupa/vinylmusicplayer/discog/Discography.java

Attempt to fix (non reproducible) https://github.com/AdrienPoupa/VinylMusicPlayer/issues/469

Flush the Discog task queue on stop

---

app/src/main/java/com/poupa/vinylmusicplayer/dialogs/SongDetailDialog.java
app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/TagExtractor.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/tageditor/AbsTagEditorActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/util/MusicUtil.java

Should fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/482

Playing hide and seek with jaudiotagger - contain the VerifyError with FLAC

---

app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/OrderablePlaylistSongAdapter.java

Should fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/485

Fix crash on tapping/dragging the very fist item of the orderable playlist

---

app/src/main/java/com/poupa/vinylmusicplayer/model/Album.java
app/src/main/java/com/poupa/vinylmusicplayer/model/Artist.java

This fixes a regression caused by https://github.com/AdrienPoupa/VinylMusicPlayer/pull/467

Fix crash if the songs/albums collection is empty

---

app/src/main/java/com/poupa/vinylmusicplayer/discog/MediaStoreBridge.java

Related to https://github.com/AdrienPoupa/VinylMusicPlayer/issues/412

Disc number fallback

---

app/src/main/AndroidManifest.xml

This fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/544

Fix Android Auto regression 

---

app/src/main/java/com/poupa/vinylmusicplayer/appwidgets/base/BaseAppWidget.java
app/src/main/java/com/poupa/vinylmusicplayer/dialogs/SleepTimerDialog.java
app/src/main/java/com/poupa/vinylmusicplayer/helper/PendingIntentCompat.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java
app/src/main/java/com/poupa/vinylmusicplayer/service/notification/PlayingNotificationImpl.java
app/src/main/java/com/poupa/vinylmusicplayer/service/notification/PlayingNotificationImpl24.java

Now that the app is targeting api 31, pendingIntent need to be flag with FLAG_MUTTABLE or FLAG_IMMUTABLE or the app will crash: https://developer.android.com/guide/components/intents-filters#DeclareMutabilityPendingIntent

Resolve IMMUTABLE crash on android 12 following a change in android specification

---

app/src/main/res/values-pt-rBR/strings.xml

values-pt-rBR/strings.xml updated to latest (January 6, 2022) values/strings.xml

Updated Brazilian Portuguese translation

---

app/src/main/java/com/poupa/vinylmusicplayer/discog/Discography.java
app/src/main/java/com/poupa/vinylmusicplayer/helper/SearchQueryHelper.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/AlbumLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/ArtistLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/GenreLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/LastAddedLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/SongLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/TopAndRecentlyPlayedTracksLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/model/smartplaylist/ShuffleAllPlaylist.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MediaSessionCallback.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/mainactivity/library/LibraryFragment.java
app/src/main/java/com/poupa/vinylmusicplayer/util/PlaylistsUtil.java

Attempt to fix the following crash (appear when songs are added/removed to the library)
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at androidx.loader.content.ModernAsyncTask$3.done(Unknown Source:33)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
at java.util.TimSort.mergeHi(TimSort.java:899)
at …
```

Fix data race

---

app/src/main/java/com/poupa/vinylmusicplayer/misc/queue/StaticPlayingQueue.java

Must check if IndexedSong.index on queue is a correct index on originalQueue

fix issue #607

---

CHANGELOG.md
app/build.gradle

This will at least allow FDroid to pick up the change and release a bunch of fixes to users via this channel.
This release does not include the dynamic queue proposal (since this a major change, I'd prefer @AdrienPoupa to merge it).

Preps for v1.4.0

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/poupa/vinylmusicplayer/appshortcuts/AppShortcutLauncherActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/glide/audiocover/AudioFileCoverFetcher.java
app/src/main/java/com/poupa/vinylmusicplayer/helper/MusicPlayerRemote.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MediaButtonIntentReceiver.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java
app/src/main/java/com/poupa/vinylmusicplayer/service/notification/AbsNotification.java
app/src/main/java/com/poupa/vinylmusicplayer/service/notification/IdleNotification.java
app/src/main/java/com/poupa/vinylmusicplayer/service/notification/PlayingNotification.java
app/src/main/java/com/poupa/vinylmusicplayer/service/notification/PlayingNotificationImpl.java
app/src/main/java/com/poupa/vinylmusicplayer/service/notification/PlayingNotificationImpl24.java
app/src/main/res/values/strings.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
script/merge-feature-branches

Upgrade tools + fix crash "IllegalStateException: Not allowed to start service Intent..."
Cumulative changes from https://github.com/vinyl2-team/vinyl2/pull/3 and https://github.com/vinyl2-team/vinyl2/pull/8

upstream-contrib: Fix start service crash

---

app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/tageditor/AbsTagEditorActivity.java

Dont leave starting/ending spaces in the saved ID3 tags
A bunch of lint fixes as well

upstream-contrib: Tag editor trim spaces

---

app/build.gradle
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Bump Java to v11
JAudioTagger to v3
And other misc tools as well (gradle...)

upstream-contrib: Upgrade jaudiotagger + java

---

.github/workflows/ci.yml

Try to fix the pre-release job (due to restricted permission set on orga level)

---

app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java
app/src/main/res/values/strings.xml

This fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/668

Broader exception catch on restoring saved queue

---

app/src/main/assets/contributors.csv
app/src/main/assets/credits.html
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AboutActivity.java
app/src/main/res/layout/card_about_app.xml
app/src/main/res/layout/card_support_development.xml
app/src/main/res/values/dimens.xml
script/build-credits-page

Preview of new visual dialog with margin:

Adding marin to "Upstream contrib/about dialog" proposal

---

app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

Some missing translation or not needed anymore translation

Missing french translation

---

app/build.gradle
app/src/main/java/com/poupa/vinylmusicplayer/dialogs/ChangelogDialog.java
app/src/main/java/com/poupa/vinylmusicplayer/dialogs/MarkdownViewDialog.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AboutActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AlbumDetailActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/ArtistDetailActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/MainActivity.java
app/src/main/res/layout/dialog_markdown_view.xml

Mostly for showing paragraph breaks.
This requires a small refactoring of the MarkdownViewDialog class

Use MarkdownViewDialog to improve visualising LastFM artist bio and album wiki

---

app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/PlayingQueueAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/discog/SnackbarUtil.java
app/src/main/java/com/poupa/vinylmusicplayer/helper/MusicPlayerRemote.java
app/src/main/res/values/styles.xml
app/src/main/res/values/styles_parents.xml

On light theme, the snackbar text was black on dark grey.

Fix snackbar unreadable text

---

app/src/main/java/com/poupa/vinylmusicplayer/loader/TopAndRecentlyPlayedTracksLoader.java

Resolves https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/725

Avoid crash while loading top tracks

---

app/src/main/java/com/poupa/vinylmusicplayer/adapter/song/PlayingQueueAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/AbsPlayerFragment.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/card/CardPlayerFragment.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/flat/FlatPlayerFragment.java
app/src/main/java/com/poupa/vinylmusicplayer/util/VinylMusicPlayerColorUtil.java

Resolve https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/701

Play next color

---

.github/release.yml
script/prepare-new-release

New script, to be ran in interactive mode, to help automatize preparing a PR for a new release

Release automation

---

app/src/main/java/com/poupa/vinylmusicplayer/dialogs/BottomSheetDialog/BottomSheetDialog.java
app/src/main/java/com/poupa/vinylmusicplayer/dialogs/BottomSheetDialog/BottomSheetDialogWithButtons.java

Fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/736

"Always ask for actions" menu now works in landscape mode

---

app/src/main/java/com/poupa/vinylmusicplayer/appwidgets/base/BaseAppWidget.java

Fixes the crashes in #784 but not the null pointer exceptions.

Fix crashes that occur when the user has a widget set up

---

app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/TagExtractor.java
app/src/main/java/com/poupa/vinylmusicplayer/util/SAFUtil.java
app/src/main/res/values/strings.xml

This fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/788 and partly https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/794

Fix exception report spam on unsupported file type

---

app/src/main/java/com/poupa/vinylmusicplayer/dialogs/helper/DeleteSongsDialogAndroidR.java
app/src/main/res/values/strings.xml

This fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/782

Fix permission request music folder crash

---

app/src/main/java/com/poupa/vinylmusicplayer/util/FileUtil.java

This fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/792

Fix Folder view, where files with non-latin characters not showing

---

script/prepare-new-release

Looks like the prepare-new-release has some minor issue.

Fix prepare-new-release script

---

CHANGELOG.md
app/build.gradle
app/src/main/assets/contributors.csv

Initially this PR is created to start a review process for the next release.
However, I just realised that the existence of the new tag (1.5.4) has triggered a build and release to PlayStore (cf https://github.com/VinylMusicPlayer/VinylMusicPlayer/actions/runs/6512049004) - oops, this is not intentional.

Next release 1.5.4

---

app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java

Might happen on low resource cases, where the handler thread is terminated while the main UI thread tries to pass it a message.
Fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/542

Fix race condition

---

app/src/main/java/com/poupa/vinylmusicplayer/glide/audiocover/AudioFileCoverFetcher.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/MainActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/mainactivity/folders/FoldersFragment.java
app/src/main/res/menu/menu_drawer.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml

Support SD card. Credits to @krebsd.
The fix is originally posted in https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/586.
I've reapplied here, and fixes the merge conflict.
This fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/626

Support SD card

---

app/src/main/java/com/poupa/vinylmusicplayer/discog/SnackbarUtil.java
app/src/main/java/com/poupa/vinylmusicplayer/glide/BlurTransformation.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MediaSessionCallback.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/mainactivity/folders/FoldersFragment.java
app/src/main/java/com/poupa/vinylmusicplayer/util/CustomArtistImageUtil.java

Minor fixes, reduce the use of app-wide context where (i.e. `getApplicationContext()`) where possible

App context fixes

---

app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AboutActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/SettingsActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/util/OopsHandler.java
app/src/main/java/com/poupa/vinylmusicplayer/util/PreferenceUtil.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/pref_development.xml

Add a new setting to control the crash report collection (by default is disabled).
(There is a pending extensive refactoring of this oops-handler, aim to be less instrusive - will push in another PR).

Add settings to opt-in for crash report

---

app/src/main/res/values-ru/strings.xml

Few strings has been added, so…

Correct and update russian translation

---

app/src/main/java/com/poupa/vinylmusicplayer/glide/audiocover/AbsCoverFetcher.java

Revert non-intended change

---

app/src/main/java/com/poupa/vinylmusicplayer/dialogs/BlacklistFolderChooserDialog.java

Blacklist error on android 12

---

app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java
app/src/main/java/com/poupa/vinylmusicplayer/util/OopsHandler.java
app/src/main/java/com/poupa/vinylmusicplayer/util/SAFUtil.java

Fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/919

Report original filename with error

---

app/src/main/java/com/poupa/vinylmusicplayer/loader/LastAddedLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/loader/TopAndRecentlyPlayedTracksLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/model/Album.java
app/src/main/java/com/poupa/vinylmusicplayer/sort/SongSortOrder.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/PlaylistDetailActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/util/ComparatorUtil.java
app/src/main/java/com/poupa/vinylmusicplayer/util/PreferenceUtil.java
app/src/main/res/values/ids.xml
app/src/main/res/values/strings.xml

Add extra option (in the detailed playlist view) to group the songs by album.

Not recently played/Last added - group by album

---

app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/AbsPlayerFragment.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/PlayerAlbumCoverFragment.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/card/CardPlayerFragment.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/flat/FlatPlayerFragment.java

Fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/845

Refactor {card|flat} fragments, move common code to base class and fix NPE

---

app/src/main/java/com/poupa/vinylmusicplayer/service/MultiPlayer.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java

This amends the #963 to maintain compat with older devices

Restore previous code to maintain compat with different version of Android

---

app/src/main/java/com/poupa/vinylmusicplayer/glide/audiocover/SongCoverFetcher.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java

Attempt to fix stale notification

---

app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java

Reported here https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/946#discussion_r1520313572

Fix crash on init with API 19

---

app/src/main/java/com/poupa/vinylmusicplayer/loader/TopAndRecentlyPlayedTracksLoader.java
app/src/main/java/com/poupa/vinylmusicplayer/provider/HistoryStore.java
app/src/main/java/com/poupa/vinylmusicplayer/provider/SongPlayCountStore.java

End the DB transaction properly (in case of failure)

---

app/src/main/java/com/poupa/vinylmusicplayer/util/SAFUtil.java

Hotfix for regression introduced by PR #989

---

app/src/main/java/com/poupa/vinylmusicplayer/adapter/album/AlbumAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/adapter/artist/ArtistAdapter.java
app/src/main/java/com/poupa/vinylmusicplayer/dialogs/SongDetailDialog.java
app/src/main/java/com/poupa/vinylmusicplayer/discog/DB.java
app/src/main/java/com/poupa/vinylmusicplayer/discog/MediaStoreBridge.java
app/src/main/java/com/poupa/vinylmusicplayer/discog/MemCache.java
app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/MultiValuesTagUtil.java
app/src/main/java/com/poupa/vinylmusicplayer/helper/M3UWriter.java
app/src/main/java/com/poupa/vinylmusicplayer/helper/menu/SongMenuHelper.java
app/src/main/java/com/poupa/vinylmusicplayer/model/Album.java
app/src/main/java/com/poupa/vinylmusicplayer/model/Song.java
app/src/main/java/com/poupa/vinylmusicplayer/service/MusicService.java
app/src/main/java/com/poupa/vinylmusicplayer/sort/AlbumSortOrder.java
app/src/main/java/com/poupa/vinylmusicplayer/sort/SongSortOrder.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/activities/AlbumDetailActivity.java
app/src/main/java/com/poupa/vinylmusicplayer/ui/fragments/player/AbsPlayerFragment.java
app/src/main/java/com/poupa/vinylmusicplayer/util/MusicUtil.java
app/src/main/java/com/poupa/vinylmusicplayer/util/NavigationUtil.java
app/src/main/res/values/strings.xml
app/src/test/java/com/poupa/vinylmusicplayer/StaticPlayingQueueTest.java

Multi artists navigation

---

app/src/main/java/com/poupa/vinylmusicplayer/discog/MemCache.java

Related to regression introduced by #992

Regression from #992 (mutli-artist-navigation)

---

app/src/main/java/com/poupa/vinylmusicplayer/misc/queue/StaticPlayingQueue.java

Fix crash described by #1008

---

app/src/main/java/com/poupa/vinylmusicplayer/discog/tagging/TagExtractor.java

Fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/1025

Fix NPE (if there is no embedded tag)

---

app/src/main/java/com/poupa/vinylmusicplayer/util/SAFUtil.java

Fixes https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/1026, https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/1040

Reduce crash report spam for exceptions that we cannot resolve

---

app/src/main/java/com/poupa/vinylmusicplayer/service/MultiPlayer.java

…and add crash dump collection for troubleshooting

Fix https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/1017 

---

app/src/main/java/com/poupa/vinylmusicplayer/dialogs/SleepTimerDialog.java

Trying to allow the sleep timer seekArc to reach 0 and the song ends immediately...
- Changed val text change to 0 if empty.
- Changed seekArc min value to 0 under onProgressChanged.

Allow sleep timer to reach 0, resolving issue #1054
